name: CI

on:
  push:
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Restore bin
      uses: actions/cache@v2
      with:
        path: ./bin
        key: ${{ runner.os }}-bin-${{ hashFiles('**/go.sum') }}

    - name: Linting
      run: make lint
    
    - name: Cache bin
      uses: actions/cache@v2
      with:
        path: ./bin
        key: ${{ runner.os }}-bin-${{ hashFiles('**/go.sum') }}
